canjs/bit-docs-html-canjs

- package.json
- static/base.less
- static/canjs.less
- static/footer.less
- static/header.less
- static/layout.less
- static/mixins.less
- static/sidebar.less
- static/typography.less
- static/variables.less
- templates/footer.mustache
- templates/header.mustache
Basic setup for HTML & CSS. 
Made with <3 for @justinbmeyer
> CSS Updates

- static/base.less
- static/sidebar.less
- static/variables.less
Just a few minor adjustments before I leave for the day. I didn't adjust the indentation on stuff like "Prototype" yet
> Just a few tweaks

- static/sidebar.less
> Sidebar bug fix.

- static/canjs.less
- static/content.less
- static/module-list.less
- static/variables.less
- templates/layout.mustache
Adds CSS for the list of modules on the homepage
> Home projects

- .editorconfig
- make-example.js
- package.json
- static/canjs.js
- static/content.less
- static/toc.js
- templates/content.mustache
This adds the table of contents to pages. It is dynamically created from
the h2s on the page. As the user scrolls it becomes sticky and shows the
h2 that the user is currently viewing. If the user hovers over the
header it will show the full TOC menu.
> Generate a table of contents

- static/buttons.less
- static/canjs.less
- static/mixins.less
Adding this in anticipation of needing buttons styles in the future:
> Adding button styles

- static/sidebar.less
- templates/header-left.mustache.html
> added styles to fix sidebar item spacing

- static/content.less
- static/header.less
- static/layout.less
> edited bitovi bit on hover and toc arrow on hover 

- static/canjs.js
> Scroll article body to top after navigation

- static/content.less
For #34
Keeps return tags on the same line.
> Add inline style to Returns block

- static/content.less
> fixes #17 depricated warning styles

- static/content.less
- static/type.less
- static/variables.less
> fixes #56 Blockquote styles

- static/canjs.js
> Add popstate listener to support back/forward navigation

- static/canjs.less
- static/demo.less
> Add demo.less back into compiled css

- static/content.less
> fixes deprecated warning styles to match blockquote styles

- static/content.less
> removed width style from videos

- templates/helpers.js
> docObject context is `this` in helpers

- templates/breadcrumb.mustache
> Disable click for On This Page dropdown title

- static/demo.less
> added styles for demo tabs - for #96

- static/header.less
> adjusted line hieght on breadcrumb link to account for change in font

- static/canjs.js
- templates/breadcrumb.mustache
For #94.
Found workaround here: https://github.com/jsbin/jsbin/issues/2819
> 94 jsbin workaround

- templates/footer.mustache
> fixes #101 - updated copy on footer

- static/canjs.js
> Change link override to current hostname only

- static/header.less
- static/mixins.less
> Increased drop-shadow on TOC dropdown

- static/content.less
- static/header.less
- static/mixins.less
Removed 15px border-left and 2px border-right.
Added 1px border around entire signature.
> Signature update

- templates/helpers.js
- templates/menu.mustache
> Add sort function to order "/" before "-".

- templates/helpers.js
> Fix customSort helper to avoid explicitly sorted objects

- static/canjs.js
- static/demo.less
> 96 demos active tab

- static/canjs.js
> 82 scroll position popstate

- static/canjs.js
> Fix canjs logo link

- static/canjs.js
For #122 
Fallback to force reload if ajax fails or content cannot be found in response data.
> Add reload fallback to ajax content failure

- static/canjs.js
> Add github button initialization on link

- static/mobile.less
> Add full width when in mobile without sidebar

- static/layout.less
> Add touch scroll for mobile safari

- package.json
- static/content.less
> Add float to code block to fill container

- docMap.json
- package.json
- static/canjs.js
- templates/layout.mustache
> Add google analytics support.

- templates/helpers.js
- templates/layout.mustache
- templates/social.mustache
Fixes the absolute image path issue.
> 33 social images

- static/content.less
closes #64 
@justinbmeyer let me know if this is what you had in mind. Should match DoneJS now.
> Updates for code styles

- static/canjs.js
- templates/helpers.js
> Set page title on any navigation

- templates/title.mustache
> Change npm badge to use package name

- static/canjs.js
- templates/helpers.js
- templates/layout.mustache
Split into more functions.
Fix .load issues
Fix undefined title on load
> Remove shared init function

- static/article-title.less
> Remove title-footer margin

- make-example.js
- static/breadcrumb.less
- static/header.less
- static/mixins.less
- static/sidebar.less
- templates/header-left.mustache
- templates/header-right.mustache
- templates/helpers.js
For #147 and #119
Removed flex stuff and tested in Chrome, Safari, and Firefox.
> 147 version dropdown

- static/canjs.js
For https://github.com/canjs/canjs/issues/2618
> Give left a min-width to allow nav hiding

- static/canjs.js
> Remove On This Page and Table of Contents with one header

- static/header.less
> Add static height to top header

- static/canjs.js
For #172 
I expect this will fix the issue, but can't replicate it locally. Will need to be deployed and checked before closing the issue.
> Add flag to prevent queueing links

- static/breadcrumb.less
- static/canjs.js
- templates/breadcrumb.mustache
> Prevent links from showing hidden nav bar.

- static/canjs.js
> Hide dropdown for touch devices

- static/sidebar.less
> Hide search bar in mobile

- static/canjs.js
> Add interval to maintain scroll until user interruption

- static/breadcrumb.less
- static/header.less
- static/img/down_black.svg
- static/img/down_white.svg
> Various IE11 styles bug fixes

- static/canjs.less
- static/screenshots.less
This adds CSS for better styling the screenshots per https://github.com/canjs/canjs/issues/2753
> Styling screenshots

- templates/helpers.js
> Fixes the navigation for modlets in modlets.

- package.json
- static/canjs.js
More info about the issue: https://github.com/canjs/bit-docs-html-canjs/issues/200#issuecomment-276222892
Fixes #200
> Fix Safari scrolling issue

- templates/helpers.js
- templates/title.mustache
> change "source" to "View page on GitHub"

- static/header.less
- templates/header-right.mustache
Fixes https://github.com/canjs/canjs/issues/2739
> Fix right menu links and reduce Bitovi logo size

- static/mobile.less
- static/sidebar.less
- static/variables.less
> Fixes bug where resizing page with open menu breaks things

- static/mobile.less
I made a terrible mistake and hide the sidebar. This should undo my mistake.
> Revert bad styles :(

- static/mobile.less
- static/sidebar.less
- static/variables.less
Really fix the sidebar I broke this time.
> Revert all my bad style changes :(

- static/mobile.less
- static/sidebar.less
- static/variables.less
This time the menu isn't borken on desktop :)
__Before__:
__After__:
__Desktop__:
> Fixes bug scrolling to the top in IOS #224

- static/canjs.js
> #240 - only pushState for links with same protocol window

- static/canjs.js
- static/search.js
> #242 - rewrite search to es5

- .gitignore
- static/canjs.js
- static/highlight-keywords.js
- static/search.js
- static/search.less
> Added search term highlighting

- docMap.json
- static/article-title.less
Related to https://github.com/canjs/canjs/pull/3273
> Added supporting styles for hero images

- static/article-title.less
- static/header.less
- static/mixins.less
- templates/title.mustache
> Moved buttons inline with the title. closes #236

- static/templates/search-results.stache
Fixes https://github.com/canjs/bit-docs-html-canjs/issues/272
> Remove quotes from search keyword

- static/search.js
> Prevent localStorage from throwing in private browsing mode safari

- static/breadcrumb.less
> Upped font-weight of On this page section

- static/search.js
> Fix storing items in local storage

- static/canjs.js
- static/layout.less
- static/search.js
- static/search.less
The start of this gif demonstrates a reload.
> 286 sidebar width

- static/search.less
- Remove the dark border-left
- Change the highlight color from green to gray
Before:
After:
> Remove color from the search results

- static/search.js
- static/search.less
> Don't hide search after selecting result

- static/canjs.js
- static/search.less
It’ll be re-enabled in a future version.
> Temporarily disable search

- static/breadcrumb.less
- static/canjs.js
- static/mixins.less
- templates/breadcrumb.mustache
@chasenlehara here is the breadcrumb menu fix.
> fix css issues with breadcrumb nav

- test/search.js
Lunr 2.1.0 seems to fix the problem. I've added a test to ensure correctness.
> Added test for define/map. Closes #312

- templates/nav-links.mustache
> Fixed #309 data-count-api warning in console.

- static/search.less
- templates/search-results.stache
> Fixed bug causing subtitle to spill out of it's container

- static/search.less
> Fix unnecessary line breaks in search results

- static/search.js
> Fix broken search results in Safari

- templates/title.mustache
> Added star count to button in page title

- static/search.js
> Scroll to top of search results when making a new search

- bit-docs.js
- build-search-worker.js
- make-example.js
- package.json
- static/search.js
This updated the `search-worker` build process to use the new `staticDist` option added here https://github.com/bit-docs/bit-docs-generate-html/pull/41
> Fix ugly build setup

- static/search.js
> Don't scroll to top of search results after clicking one

- static/layout.less
- static/sidebar.less
> Fix being able to scroll completely to the bottom of the nav

- .travis.yml
- firefox-allow-popups.sh
- package.json
- readme.md
- sidebar/test.js
- test.sauce-labs.js
- test/search.js
Also fix some issues in the code that were preventing it from running correctly in some browsers.
Closes https://github.com/canjs/bit-docs-html-canjs/issues/399
> Set up Sauce Labs

- package.json
- static/base.less
- static/breadcrumb.less
- static/content.less
moved to [bit-docs/bit-docs-prettify](https://github.com/bit-docs/bit-docs-prettify/pull/17)
> remove line-highlight code

- package.json
- test.sauce-labs.js
> chore(package): update test-saucelabs to version 0.0.6

- build-search-worker.js
> remove service worker workaround from search build

- templates/nav-links.mustache
Fixes https://github.com/canjs/bit-docs-html-canjs/issues/511
> Highlight the current section in the main nav

- static/header.less
> Animates hover in place

- static/toc.less
- templates/content.mustache
> Remove paragraphs and icons

- static/demo.less
- static/header.less
- static/loading-bar.less
- static/mobile.less
- static/screenshots.less
- static/search.less
- static/variables.less
> fixed demo tab z-index and created z-index variables

- static/canjs.js
- static/layout.less
> Only show the sidebar TOC scrollbar when hovering

- static/canjs.js
- static/header.less
- static/sidebar.less
- static/variables.less
- templates/content.mustache
Also clean up some styles for the By Bitovi logo.
Fixes https://github.com/canjs/bit-docs-html-canjs/issues/549
[The gif below looks odd because it opens a new tab and only part of the new page is seen.]
> Fix the links in the mobile menu

- test/search.js
Fix a test to make sure it is running.
> Update the test to make build pass

- package.json
- test/search.js
This should fix some stability issues with the tests.
> Upgrade to StealJS 2 & QUnit 2
