- static/base.less
- static/canjs.less
- static/content.less
- static/variables.less
- templates/signature.mustache
This PR has some better spacing for paragraphs and uls/ols in the content overall. 
BUT it also includes a proposed design for both signatures and parameters. Note, I haven't done options or returns yet... @justinbmeyer please have a look and let me know what you think. I wasn't able to find a way to avoid having at least the Signatures in a bordered-container. 
Oh! Also, I made `<code>` with red-colored text and I liked it. But it's a simple change, if you don't think it works. It seems like just the right amount of stand-out-ness.
> Content tweaks, Signature & Parameters

- static/footer.less
- static/header.less
- static/layout.less
- static/sidebar.less
- static/variables.less
- templates/content.mustache
- templates/layout.mustache
- templates/sidebar.mustache
This PR adds a flyout / off-canvas sidebar for devices smaller than the breakpoint (currently 700px). 
- Above the breakpoint, we still get nice flexbox columns
- The "menu" button appears in the header, but is fixed position so it's always available no matter where you are on the page.
> Mobile menu

- static/base.less
- static/content.less
- static/variables.less
- templates/content.mustache
- templates/signature.mustache
- templates/title.mustache
This modifies parameters and returns to have the same indentation. I did that partly by removing the indentation from parameters, but this might have a negative effect on nested parameters. I'll need to check. I opened https://github.com/canjs/bit-docs-html-canjs/issues/19 to address the returns being on 2 lines
Also adds support for "types" like page, stylesheet, etc.. next to the title which is needed for https://github.com/canjs/bit-docs-html-canjs/issues/11
Also adds placeholder styles for the depreciated warning for https://github.com/canjs/bit-docs-html-canjs/issues/17
Finally, I started on the "On this page" menu at the top but I think I'll need help making the JS work before I do much more of the CSS. Maybe @matthewp can help me with that part? This is …
> API updates

- static/content.less
> fixes #63 style videos

- static/content.less
- static/variables.less
Added medium gray border and light gray background.
Width of video is set to 100% until it reaches 1000px, then it stays at 1000px.
> fixes video styles by adding light gray border and width

- static/content.less
For #139 
I left out `width:100%` that was supposed to be included in the `float:left` fix, but that still didn't quite work correctly. A better fix is using a `min-width` with `inline-block`.
> Fix code block expansion styles

- templates/menu.mustache
For #24
This was reverted somewhere along the line.
> Add sidebar custom sorting

- static/breadcrumb.less
- static/canjs.js
- templates/breadcrumb.mustache
For #173
A bug was introduced to the `getHeaders` function when adding the Table of Contents hide for any article with less than 2 headers. The On This Page dropdown only works with `h2` elements. Only the TOC should use the outline level.
This also adds hiding to the On This Page breadcrumb when empty. Previously only the dropdown was hidden.
> Fix getHeaders function to re-enable on this page dropdown

- static/breadcrumb.less
This uses the box-shadow mixing to make the On this Page menu stand out more. I'm going to say closes #87 because I want to move the other part of 87 into a new issue.
> Use box-shadow mixin

- static/module-list.less
fixes #170 but feels very much like a small hack. I have no idea why this link positions itself like this. Wrapping the whole thing inside a `<p>` also fixes it, but we can't control that since the markdown generator is what creates this HTML. Oh well.
> Link margin

- static/header.less
This fixes #191 but tbh it shouldn't be positioned using padding like that. And imo the logo is too small. I think this area could use a small CSS re-factor when there's time.
> Version padding

- static/canjs.js
When the user holds down `alt`, `ctrl`, `shift`, or another `meta` key, we won’t use `pushState` to handle the clicked link.
Demo of holding command on macOS:
Fixes #203
> Don’t use pushState if a modifier key is being held down

- templates/helpers.js
Retrieve the actual closest package to docObjects that had their
parent's name set to some name higher up in the family tree.
Resolves #204
> Fix broken source links

- templates/helpers.js
It appears that [line number](https://github.com/canjs/bit-docs-html-canjs/blob/master/templates/helpers.js#L245) was a zero-based index. Adding `+1` fixes the issue.
> Fixed issue where source links were off by one line

- templates/helpers.js
Fixes bug that crashes `bit-docs` when pointing parent tag at something with no package.json.
```
/Users/austin/bitovi/canjs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:155
throw e;
^
TypeError: Cannot read property 'version' of undefined
at Object.sourceLink (/Users/austin/bitovi/canjs/node_modules/bit-docs/lib/configure/node_modules/bit-docs-generate-html/site/templates/a57f5957978cb5171aef5ac6ec87cd7d/helpers.js:243:54)
at program6 (eval at createFunctionContext (/Users/austin/bitovi/canjs/node_modules/bit-docs/lib/configure/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:189:23), <anonymous>:53:118)
at Object.prog [as fn] (/Users/austin/bitovi/canjs/node_modules/bit-docs/lib/configure/node_modules/handlebars/dist/cjs/handlebars/runtime.js:118:12) …
```
> Fixed source link herlper

- static/article-title.less
Otherwise the li is block, and the cursor is a pointer where there's not actually a click target.
> Move cursor pointer css from li to a

- static/search.js
> #244 - wait until we have a new searchMap before clearing the old one

- static/canjs.js
- static/search.js
- templates/layout.mustache
resolves #249 
* fix scope for links in search renderer helper
* graceful fallback if searchMapHash file not found but still have localStorage
* use element attribute instead of script to set pathPrefix
* recover from a page not having a nav
> search links and search disappearance

- templates/helpers.js
- templates/title.mustache
Resolves #255.
Assumes the page parent repository is either the same as the NPM module name in the path to the page, or if the page is not inside node_modules, the repository is 'canjs'.
> Fix link pathing

- static/templates/search-results.stache
Originally I had fixed the double escaping here bit-docs/bit-docs-generate-searchmap#4, but CommonMark encodes entities and had no option to disable that functionality so I have opted to fix it here instead.
> Fixed double escaped characters in search

- static/article-title.less
Several small bugs at certain sizes became apparent, so I tested it much more thoroughly and fixed what I found.
__Desktop:__
__iPhone 5:__
__iPhone 6:__
__iPhone iPad:__
> Fix responsive buttons

- static/breadcrumb.less
- templates/breadcrumb.mustache
- Refactoring the menu so the <a> has the padding and <li> is just the
wrapper
- Separating the / as an individual li
- Reversing out the background when selected
- Removing the caret triangle altogether
> Updates to On This Page CSS

- static/search.less
Moved search input up by `2px` under the advice of @jamiemccue.
__Before:__
__After:__
> Align the search icon and placeholder

- package.json
- static/search.js
- test/browser.js
- test/search.js
This PR rewrites how we query the Lunr index to get search results. I’ve added tests for a few scenarios—if you test search and find that the results aren’t great for a specific term, I can add a new test case for it and fix the results.
Fixes https://github.com/canjs/bit-docs-html-canjs/issues/290
> Improve the search result ordering

- static/search.js
- test/search.js
Fixes https://github.com/canjs/bit-docs-html-canjs/issues/279
> Fix searching for terms like “%special”

- static/search.js
Before:
After:
Fixes https://github.com/canjs/bit-docs-html-canjs/issues/274
> Truncate results to 50

- static/search.js
- test/search.js
Searching for modules like can-compute was _really_ slow. This commit optimizes those queries by not also doing a fuzzy search.
> Improve the speed of searching for can-*

- static/layout.less
- static/search.js
- static/search.less
- static/sidebar.less
- static/variables.less
- templates/search-bar.mustache
Previously, when the user would start a new search and the results would open, the sidebar would jump to a specific width and then animate the rest of the width change.
This fixes the styles so the sidebar animates smoothly to its new width.
> Fix opening search animation

- static/templates/search-results.stache
This prevents html elements that should show up as code from being inserted into the DOM.
Before:
After:
> Escape the description

- templates/helpers.js
This commit fixes an issue with `@subchildren` preventing grandchildren from being shown.
> Fix issue with @subchildren

- static/article-title.less
Before:
After:
Fixes https://github.com/canjs/bit-docs-html-canjs/issues/280
> Fix the tortoise & hare images on mobile

- templates/helpers.js
Array’s sort method expects a number, not a boolean.
> Fix ordering children within a group

- templates/title.mustache
> Fix edit on github link on non-module pages

- static/content.less
I don't think this was needed and it was causing a little style bug.
__Before__:
__After__:
> Removed width atribute

- package.json
- static/canjs.js
- static/search.js
Since we want the site to work when hosted from a parent folder, and the search results persist through navigation, the `pathPrefix` must be dynamically set and the results must be re-rendered when navigation occurs to ensure links don't point to the next directory up e.g. `/doc/...` instead of `/canjs/doc/...` .
> Make search links relative

- static/canjs.js
It certain input can cause catastrophic backtracking. https://regex101.com/r/MMBcMM/1
> Fix catastrophic backtracking ReqExp. Closes #336

- static/search.js
This click listener was redundant and causes the `navigate()` to fire twice. The only listener needed is https://github.com/canjs/bit-docs-html-canjs/blob/master/static/canjs.js#L35
> Removed redundant click listener

- static/canjs.js
- static/mobile.less
The CanJS menu uses an `<input type="checkbox">` wrapped with a `<label>` with some fancy CSS. No JS whatsoever. The native behavior of a browser does not check a focused checkbox when the user presses enter.
> Toggle focused checkbox elements on enter keypress

- package.json
- static/search.js
> Active search result sticks to bottom and top of page

- static/canjs.js
> Scroll nav to current menu item

- static/search.less
- templates/search-results.stache
> Fix escaping in search results and added styles

- static/canjs.js
- static/layout.less
- static/sidebar.less
- templates/content.mustache
> Fix #354 Search results on certain pages are getting pushed up

- static/search.js
I just realized that the number wasn’t bumped when [these changes](https://github.com/canjs/bit-docs-html-canjs/commit/00d068d2423f2ab123440fd0587366fb2c2c991d) were made, so bumping it now.
> Bump the search index version

- test/search.js
When hosting the site from a parent folder, `/doc` will lead to a 404. `../doc` will look up 1 folder from `/test` so it will work with or without a parent folder.
> Fix test pathPrefix

- .travis.yml
- readme.md
- static/search.js
Also:
- Pin Travis to Firefox 51
- Add some badges to the README
> Fix results for “define/map” in recent version of Firefox

- make-example-search-worker.js
- package.json
- static/loading-bar.js
- static/search-logic.js
- static/search-worker.js
- static/search.js
- test/search.js
This takes all of the Lunr code and moves it to a web worker, so the indexing and searching process doesn’t block the main thread. This also adds a loading indicator when a search is being performed, which isn’t visible if the main thread is locked, hence the need for using a web worker.
This is a WIP because:
Before:
After:
> WIP: Move search into a web worker

- static/sidebar.less
In some browser/OS combinations, an ugly scroll bar shows up in the sidebar.
> Remove ugly scroll bar in the search results

- static/search.js
When I fixed the Safari bug, I inadvertently sanitized the descriptions that are printed to the UI.
> Fixed bug that removed all HTML from search results

- static/canjs.js
We highjack clicks on `<a>` tags and use Ajax to load the content in. If we don't change the URL with `pushState` before we load the content into the DOM, all relative paths will be based off the previous page's URL. This causing the issue Justin reported in slack: https://bitovi.slack.com/archives/C09R50SAE/p1499289090158230
> Fix a bug causing resources with relative paths to load the wrong URL

- static/canjs.js
> Fix #373 Go back and go forward functionality broken

- static/search.js
- static/search.less
Similarly, don’t go to the last result after keyboarding past the first result.
Also:
- Make the entire area around a search result clickable. Previously, only the text was clickable to select a search result.
- Remove extraneous padding from the top and bottom of the search results
> Don’t go to the first result after keyboarding past the last result

- static/canjs.js
If a page is loaded and it doesn’t have a nav, then we won’t try to replace the current nav.
Before:
After:
> Handle edge case where a page doesn’t have a nav

- static/breadcrumb.less
- static/canjs.js
- static/header.less
- static/layout.less
- static/search.js
- static/search.less
- static/sidebar.less
- static/variables.less
- templates/content.mustache
Instead of relying on flexbox to correctly lay out the absolutely-positioned overlay, we’re specifying an exact top position and height for it, which consistently renders correctly in all browsers.
I also cleaned up some of the CSS classes and styles.
Before:
After:
Fixes https://github.com/canjs/bit-docs-html-canjs/issues/383
> Fix the search results overlay in Safari

- static/home.less
Before:
After:
Related to https://github.com/canjs/canjs/issues/3224
> Fix some styles for the “Getting started” section on the home page

- static/canjs.js
- static/search.less
Previously, if the user scrolled down a page on desktop and the black breadcrumb bar moved to the top, the search results pane would not have the correct height.
Before:
After:
> Fix issue with the position of the search results after scrolling the page

- static/loading-bar.js
Fix bug preventing loading indicator from showing
Since we have a CSS animation on the width of the bar, and on a fast network the progress event usaully only fires once (at 100%), hiding the loading indicator eminently after calling `.end()` would not allow the animation to complete before the bar hidden.
This PR adds a timer to wait for the CSS animation before hiding the bar.
closes #392
__Desktop:__
__Mobile:__
__Slow 3G Mobile:__
> Fix bug preventing loading indicator from showing

- static/canjs.js
- static/canjs.less
- static/layout.less
- static/survey-ad.js
- static/survey-ad.less
- templates/content.mustache
- templates/survey-ad.mustache
The `survey-ad` control is shown at the bottom of every page. If you click almost anywhere in the bar, the survey landing page will open in a new tab/window.
At the far right of the bar, there’s a close button that will animate the bar out of view and store the current time in localStorage. When the page first loads, we check for the presence of that localStorage item to decide whether the bar should be shown or not.
The bar is only enabled for desktop (1000px+ wide) screens. The only bug I’ve found is when you use search while the bar is still present; in that situation, you can see all of the search results, but the scroll bar goes under the bar. I don’t think that’s a blocker.
Screenshot:
Gif showing how it interacts with the rest of the content & sidebar:
> Add a bar that advertises the community survey

- sidebar/sidebar.events.js
Some browsers version dont support [```NodeList.prototype.forEach```](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach) like firefox < v50 which causes an error, using  ```can-util/js/each/each``` fixes the issue in the new sidebar.
> use can-util/js/each/each instead of NodeList.prototype.forEach

- bit-docs.js
- make-example.js
- package.json
- static/canjs.js
- static/header.less
- static/layout.less
- static/mixins.less
- static/module-list.less
- templates/layout.mustache
This fixes the most critical issues in IE 11:
- Flexbox layout is fixed so content shows up
- The old sidebar was being kept alongside the new sidebar
- Links weren’t working in the new sidebar
- The API Docs page would take upwards of 30 seconds to load because of the GitHub star buttons, so those links are _not_ upgraded to buttons in IE anymore
Current CanJS.com:
After updates (images are broken because the screenshot’s from this repo):
Closes https://github.com/canjs/canjs/issues/3619
> Fix critical issues in IE 11

- sidebar/README.md
- sidebar/sidebar.viewmodel.js
- sidebar/test.js
Previously, when a page within a package that is not part of the Core collection was selected, the group that it’s in would not automatically be expanded. This bug was apparent on this page: https://canjs.com/doc/can-view-nodelist/types/NodeList.html
This PR also adds some docs about the sidebar.
> Fix an issue with groups not being expanded when a page in a non-Core package is selected

- sidebar/sidebar.events.js
To the best of my knowledge, the best way to handle this is to check for properties on the event object that indicate a modifier key is being held down.
Closes https://github.com/canjs/bit-docs-html-canjs/issues/414
> Fix how links are handled when a modifier key is pressed

- static/canjs.js
Previously, if you clicked on a link to a hash section and then clicked another link to a hash section, the second click wouldn’t work.
This is fixed by correctly determining the hash you’re navigating to and from. Additionally, this fixes an issue in Firefox where the “On this page” navigation wouldn’t be updated with the correct title, and an issue in Chrome which would cause the navigation to be hidden when using the browser’s back button.
Fixes https://github.com/canjs/bit-docs-html-canjs/issues/420
> Fix navigating to and from URLs with hashes

- static/screenshots.less
This small helper class helps improve the display of screenshots in the docs, specially making sure the image does not overflow the container.
took me a while to test the integration, but it works.
> Style screenshots

- static/article-title.less
- static/canjs.js
- static/content.less
- static/mixins.less
There were a couple styles that competed with Prism for bit-docs/bit-docs-prettify#15.
Specifically: a margin on `article pre code` and a border radius on `code`.
With this fix (and with prism), it looks like:
> remove styles competing with prism

- templates/search-results.stache
- test/search.html
- test/search.js
Due to not fixing some scope warnings before upgrading to CanJS 4, the search results weren’t rendering anything.
Before:
After:
> Fix search

- static/base.less
- static/header.less
- static/layout.less
- static/mobile.less
- static/sidebar.less
- static/variables.less
Bring back 'Find in Page' highlights in scrollbar
Allows for user to scroll to top in mobile by tapping the status bar
Keeps the same functionality as the current live side with the sidebar
closes #507
> Fixes scrolling issues

- static/header.less
Changed branding and version to be `display: flex;`, to align center, and applied the header height variable to those sections to disallow a gap between the hit state and the hover state.
> Adds a height to the brand and version to overlap with hover state

- sidebar/test.js
- static/base.less
- static/canjs.js
- static/header.less
- static/layout.less
- static/mixins.less
- static/mobile.less
- static/sidebar.less
- static/variables.less
- templates/content.mustache
> Updates styles for sidebar and cleans up CSS

- static/layout.less
This removes setting `overflow` from `sidebar/#left` column from the style `layout.less`.
The scrollbar is visible without having `overflow-y` property.
Tested in `Firefox V66.0.5`, `Chrome V74.0.3729.131`, `Safari` and `Edge`.
Closes #523
> i523 remove overflow from sidebar/#left column

- templates/helpers.js
- templates/layout.mustache
This adds `description`, `og:description`, `og:image`, `og:title`, and schema to every page.
I looked into the schema and decided that `SoftwareSourceCode` was a better `@type`, and then I changed the keys/values that are included based on that.
This PR doesn’t change the homepage title. That’ll be done in a separate PR.
Part of https://github.com/canjs/bit-docs-html-canjs/issues/497
Below is what the metadata looks like on a few pages:
> Add better metadata for SEO

- static/header.less
Small screen
Small screen brands
Small screen version
Responsive
> Version selector always visible

- static/canjs.js
- templates/helpers.js
Fixes https://github.com/bit-docs/bit-docs-generate-html/issues/44
> Generate better page titles

- static/search-logic.js
- static/search.js
- test/search.js
This improves the search results for queries such as restModel, QueryLogic, and DefineMap. This is done by:
1) Concatenating the module’s name (e.g. `can-define/map/map` is converted to `definemapmap`) and indexing the result
2) Giving preference to packages over other pages/results
Fixes https://github.com/canjs/bit-docs-html-canjs/issues/499
> Improve search results for terms like “restModel”

- static/canjs.js
- static/layout.less
- static/toc.less
- templates/content.mustache
The Get Help section is now pinned to the bottom right of the sidebar. The TOC portion of the sidebar is its own independently-scrollable area.
@jamiemccue, please let me know if there’s anything you think we should change about the design/layout.
Fixes https://github.com/canjs/bit-docs-html-canjs/issues/530
Even when the TOC is not very long, the Get Help links stick to the bottom of the right sidebar:
When the TOC is longer, it gets cut off by a border between it and the Get Help links:
Here’s what it looks like when you scroll down the page and scroll inside the TOC:
Some pages don’t have a TOC. The Get Help links still stick to the bottom:
> Make it so only the TOC area scrolls in the right sidebar

- static/sidebar.less
The top margin on the collection names (Core, Infrastructure, etc.) was not animating, causing a visible jump when sections were opened and closed.
Fixes https://github.com/canjs/bit-docs-html-canjs/issues/522
> Fix the animation when closing sections in the sidebar

- static/canjs.js
- templates/helpers.js
This removes from the code the part that capitalize the first letter of page title:
> Remove capitalize page titles

- static/canjs.js
- static/header.less
- static/sidebar.less
- templates/content.mustache
- templates/social.mustache
- Kept the main navigation as is because it is quite deep
- Moved the social-links below the main nav
- Centered the _By Bitovi_ logo below the social-links
> Add the by bitovi logo into mobile sidebar and reorganize the output

- static/canjs.js
This fixes https://github.com/canjs/canjs/issues/5115
The logic behind this fix is to read the script tags with `steal-module` type and define a module on the fly using steal.
This is needed for the Counter demo essentially.
> Handle inline scripts ajax

- templates/signature.mustache
This adds `data-skip` attribute to the `Returns` and `Options` headings in signature in order to be removed from TOC.
Fixes #562
> Remove headings from TOC

- static/article-title.less
- static/content.less
- static/type.less
> Updated type size, color and margin

- make-example.js
- static/canjs.less
- static/prism.less
Fixes #561 
Depends on https://github.com/bit-docs/bit-docs-html-codepen-link/pull/14
> New Copy & Run button styles implementation

- static/prism.less
Fixes #561
Before the fix:
After:
> Fix applying new button styles on signatures

- static/search-logic.js
- test/search.js
This fixes make possible to return results when searching for helper with terms like `#let` or `#if`.
fixes #589
> Handle searching for helper with terms start with '#'
